project:
  type: website
  output-dir: _site

website:
  title: "Atelier de Código"
  site-url: https://atelierdecodigo.com/en
  margin-header: subscribe-en.html
  open-graph:
    site-name: "Atelier de código"
    locale: en_US
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: contact.qmd
        text: "Contact"
      - href: posts/index.qmd
        text: "Blog"
    right:
      - text: "SPA"
        href: https://atelierdecodigo.com/index.html
      - text: "ENG"
        href: https://atelierdecodigo.com/en/index.html

format:
  html:
    theme: litera
    css: ../styles.css
    include-in-header: ../_includes/google-ads-head.html