project:
  type: website
  output-dir: docs
  

website:
  title: "Atelier de c√≥digo"
  site-url: https://atelierdecodigo.com
  description: "Un espacio para aprender a programar de forma artesanal."
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Acerca de
      - href: contact.qmd
        text: Contacto
      - href: posts/index.qmd
        text: Blog
  google-analytics: G-TDY574S9W1
  margin-header: subscribe.html

format:
  html:
    theme: litera
    css: styles.css
