project:
  type: website
  output-dir: docs
  

website:
  title: "Atelier de c√≥digo"
  site-url: https://atelierdecodigo.com
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre
      - href: contact.qmd
        text: Contacto
      - href: posts/index.qmd
        text: Blog

format:
  html:
    theme: litera
    css: styles.css
