project:
  type: website
  output-dir: docs

website:
  title: "Atelier de c√≥digo"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre
      - href: contacto.qmd
        text: Contacto

format:
  html:
    theme: cosmo
    css: styles.css
